logging:
  level:
    root: INFO
    #org.springframework.boot.autoconfigure.security: DEBUG
    org.springframework.security: DEBUG
    #org.springframework.boot: DEBUG

spring:
  datasource:
    url: jdbc:h2:mem:userdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    user:
      name: user
      password: password

  sql:
    init:
      mode: always

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/session/jdbc/schema-@@platform@@.sql
      table-name: SPRING_SESSION