-- INSERT INTO users (username, password, roles) 
-- VALUES ('user', '$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG', 'USER');
-- -- The password here is the BCrypt encryption of "password"
create table users(
    username varchar_ignorecase(50) not null primary key,
    password varchar_ignorecase(100) not null,
    enabled boolean not null
);

create table authorities (
    username varchar_ignorecase(50) not null,
    authority varchar_ignorecase(50) not null,
    constraint fk_authorities_users foreign key(username) references users(username)
);

INSERT INTO users (username, password, enabled)
VALUES (
    'user',
    '{bcrypt}$2a$10$x1Q04LMJq8HX/J4AlRldZuNWIpjFevyNAP3OGUHPAbwLiGTHDVaJW',  -- 'password' 加密后的值
    true
);

INSERT INTO users (username, password, enabled)
VALUES ('admin', '{bcrypt}$2a$10$x1Q04LMJq8HX/J4AlRldZuNWIpjFevyNAP3OGUHPAbwLiGTHDVaJW', true);

INSERT INTO users (username, password, enabled)
VALUES ('superuser', '{bcrypt}$2a$10$x1Q04LMJq8HX/J4AlRldZuNWIpjFevyNAP3OGUHPAbwLiGTHDVaJW', true);




INSERT INTO authorities (username, authority)
VALUES ('user', 'ROLE_USER');

-- -- 普通用户
-- INSERT INTO authorities VALUES ('user', 'ROLE_USER');

-- 管理员
INSERT INTO authorities VALUES ('admin', 'ROLE_ADMIN');

-- 一个用户可以有多个角色
INSERT INTO authorities VALUES ('superuser', 'ROLE_USER');
INSERT INTO authorities VALUES ('superuser', 'ROLE_ADMIN');


create table groups (
	id bigint generated by default as identity(start with 0) primary key,
	group_name varchar_ignorecase(50) not null
);

create table group_authorities (
	group_id bigint not null,
	authority varchar(50) not null,
	constraint fk_group_authorities_group foreign key(group_id) references groups(id)
);

create table group_members (
	id bigint generated by default as identity(start with 0) primary key,
	username varchar(50) not null,
	group_id bigint not null,
	constraint fk_group_members_group foreign key(group_id) references groups(id)
);


-- 1. 首先创建用户
INSERT INTO users (username, password, enabled) VALUES 
    ('bob', '{bcrypt}$2a$10$x1Q04LMJq8HX/J4AlRldZuNWIpjFevyNAP3OGUHPAbwLiGTHDVaJW', true),
    ('alice', '{bcrypt}$2a$10$x1Q04LMJq8HX/J4AlRldZuNWIpjFevyNAP3OGUHPAbwLiGTHDVaJW', true);

-- 2. 创建用户组（注意：需要显式指定 ID）
INSERT INTO groups (id, group_name) VALUES 
    (1, 'ADMIN_GROUP'),
    (2, 'USER_GROUP');

-- 3. 分配组权限（现在 group_id 1和2已经存在了）
INSERT INTO group_authorities (group_id, authority) VALUES 
    (1, 'ROLE_ADMIN'),
    (2, 'ROLE_USER');

-- 4. 最后将用户加入组
INSERT INTO group_members (username, group_id) VALUES 
    ('bob', 1),    -- bob 加入 ADMIN_GROUP
    ('alice', 2);  -- alice 加入 USER_GROUP

